"""empty message

Revision ID: 76c79cee706c
Revises: e5878030ac49
Create Date: 2026-06-06 02:29:53.524136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76c79cee706c'
down_revision: Union[str, Sequence[str], None] = 'e5878030ac49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.add_column('student_profiles', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'is_verified')
    op.drop_column('student_profiles', 'is_completed')
    # ### end Alembic commands ###
